export const usersType = {
  FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_USERS_FAIL: 'FETCH_USERS_FAIL',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
};

export const organizeUserType = {
  FETCH_ORGANIZE_USER_REQUEST: 'FETCH_ORGANIZE_USER_REQUEST',
  FETCH_ORGANIZE_USER_FAIL: 'FETCH_ORGANIZE_USER_FAIL',
  FETCH_ORGANIZE_USER_SUCCESS: 'FETCH_ORGANIZE_USER_SUCCESS',
};

export const organizationType = {
  FETCH_ORGANIZATIONS_REQUEST: 'FETCH_ORGANIZATIONS_REQUEST',
  FETCH_ORGANIZATIONS_FAIL: 'FETCH_ORGANIZATIONS_FAIL',
  FETCH_ORGANIZATIONS_SUCCESS: 'FETCH_ORGANIZATIONS_SUCCESS',
};

export const taskboardsType = {
  FETCH_TASKBOARDS_REQUEST: 'FETCH_TASKBOARDS_REQUEST',
  FETCH_TASKBOARDS_FAIL: 'FETCH_TASKBOARDS_FAIL',
  FETCH_TASKBOARDS_SUCCESS: 'FETCH_TASKBOARDS_SUCCESS',
};
